### ISSUE TITLE
signature question

### ISSUE THREAD

**Issue by Paul101432** [itext/i7js-signatures#1]
when i signature like PdfStamper.getOverContent no PdfStamper.getUnderContent  .

**Comment by michaeldemey** [comment]
Hi,

To limit the amount of channels that we have to monitor we don't answer questions on GitHub. Our main channels are through our Jira, note that this is for paying customers only, or through StackOverflow.

If you repost your question on one of those, we'll gladly answer your question.

Kind regards,
Michael.
